name: Build Gutenberg Plugin Zip

on:
  pull_request:
    paths-ignore:
    - '**.md'
  push:
    branches: [master]
    paths-ignore:
    - '**.md'
  workflow_dispatch:
    inputs:
      version:
        description: 'Plugin version to release (must start with a "v")'
        required: true

env:
  VERSION: ${{ github.event.inputs.version }}

jobs:
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    if: startsWith(github.event.inputs.version, 'v')
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Update plugin version
        run: |
          cat <<< $(jq --tab --arg version "${VERSION#v}" '.version = $version' package.json) > package.json
          cat <<< $(jq --tab --arg version "${VERSION#v}" '.version = $version' package-lock.json) > package-lock.json
          VERSION_REGEX=" \* Version: [0-9]\+\.[0-9]\+\.[0-9]\+\s*"
          sed -i "s/${VERSION_REGEX}/ * Version: ${VERSION#v}/g" gutenberg.php
          OLD_VERSION_REGEX='Gutenberg \K([0-9]+\.[0-9]+\.[0-9]+(-rc\.[0-9]+)?)'
          OLD_VERSION=$(grep -oP "$OLD_VERSION_REGEX" readme.txt)
          sed -i "s/${OLD_VERSION}/${VERSION#v}/g" readme.txt

      - name: Commit the version bump
        run: |
            git config user.name "Gutenberg Repository Automation"
            git config user.email gutenberg@wordpress.org
            git add gutenberg.php package.json package-lock.json readme.txt
            git commit -m "Bump plugin version to $VERSION"
            git push

  build:
    name: Build Release Artifact
    runs-on: ubuntu-latest
    needs: bump-version
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Fetch version bump commit
        if: startsWith(github.event.inputs.version, 'v')
        run: git pull origin ${{ github.ref }}

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Build Gutenberg plugin ZIP file
        run: ./bin/build-plugin-zip.sh
        env:
          NO_CHECKS: 'true'

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: gutenberg-plugin
          path: ./gutenberg.zip

      - name: Build release notes draft
        if: startsWith(github.event.inputs.version, 'v')
        run: |
          IFS='.' read -r -a VERSION_ARRAY <<< "${VERSION#v}"
          MILESTONE="Gutenberg ${VERSION_ARRAY[0]}.${VERSION_ARRAY[1]}"
          npm run changelog -- --milestone="$MILESTONE" --unreleased > release-notes.txt
          sed -ie '1,6d' release-notes.txt

      - name: Upload release notes artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-notes
          path: ./release-notes.txt

  create-release:
    name: Create Release Draft and Attach Asset
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.event.inputs.version, 'v')
    steps:
      - name: Set Release Version
        id: get_release_version
        run: echo ::set-output name=version::$(echo $VERSION | cut -d / -f 3 | sed s/^v// | sed 's/-rc./ RC/' )

      - name: Download Plugin Zip Artifact
        uses: actions/download-artifact@v2
        with:
          name: gutenberg-plugin

      - name: Download Release Notes Artifact
        uses: actions/download-artifact@v2
        with:
          name: release-notes

      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ steps.get_release_version.outputs.version }}
          draft: true
          prerelease: ${{ contains(env.VERSION, 'rc') }}
          body_path: release-notes.txt

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gutenberg.zip
          asset_name: gutenberg.zip
          asset_content_type: application/zip
